### ISSUE TITLE
The entity name for genes, microbes, and diseases

### ISSUE THREAD

**Issue by future97** [zkxinxin/HCMGNN#1]
Hello, would it be possible for you to share the names of the biological entities corresponding to the rows in the dis_sim, gene_sim, and mic_sim files?

I look forward to your reply. Thank you very much!

**Comment by future97** [comment]
Thanks for sharing!

**Comment by zz10462** [comment]
> Thanks for sharing!

方便分享下在文件里的mircrobe, gene, disease entity ID 索引编号对应的具体名字吗？谢谢
